server:
  port: 8082
spring:
  servlet:
    multipart:
      # 设置 上传文件的大小
      max-file-size: 50MB
      # 设置 整个请求的大小
      max-request-size: 50MB

  application:
    name: Mtc-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mtc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: USA

  redis:
    host: 127.0.0.1
    port: 6379


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.tm.pojo
  configuration:
    map-underscore-to-camel-case: true


feign:
  hystrix:
    enabled: true


hystrix:
  dashboard:
    proxy-stream-allow-list: "*"